app/modules/ACP/controllers/ACPController.py
from modules.ACP.views.DashboardACPView import DashboardACPView


class ACPController:

    def dashboardAction(self):
        view = DashboardACPView()
        return view.render()

app/modules/ACP/controllers/DashboardACPController.py
from modules.ACP.views.DashboardACPView import DashboardACPView


class DashboardACPController:

    def dashboardAction(self):
        view = DashboardACPView()
        
        return view.render()

app/modules/ACP/views/ACPDashboardView.py
from modules.Language.services.LanguageService import LanguageService
from modules.Ukubuka.views.UkubukaACPView import UkubukaACPView


class ACPDashboardView(UkubukaACPView):

    def __init__(self):
        super().__init__('modules/ACP/dashboard.html')

    def _prepareTemplateData(self):
        super()._prepareTemplateData()

        languageService = LanguageService.getInstance()
        self.templateData['title'] = languageService.translate('Dashboard')

app/modules/ACP/views/DashboardACPView.py
from flask import g
from modules.Base.views.ACPView import ACPView


class DashboardACPView(ACPView):

    template: str = 'modules/ACP/dashboard.html'

    def _prepare_template_data(self):
        super()._prepare_template_data()

        self.template_data['title'] = g.t._('Dashboard')

app/modules/Base/views/ACPView.py
from modules.Base.views.View import View
from modules.Notification.entities.Notification import Notification
from modules.Notification.services.NotificationService import NotificationService


class ACPView(View):

    def __init__(self):
        super().__init__()

        self.notifications = []

    def _prepare_template_data(self):
        super()._prepare_template_data()

        self.template_data['notifications'] = self.notifications

    def info(self, text):
        self.notifications.append(Notification(text, NotificationService.INFO_TYPE))

    def warning(self, text):
        self.notifications.append(Notification(text, NotificationService.WARNING_TYPE))

    def success(self, text):
        self.notifications.append(Notification(text, NotificationService.SUCCESS_TYPE))

    def error(self, text):
        self.notifications.append(Notification(text, NotificationService.ERROR_TYPE))

app/modules/Language/controllers/ACPTranslationController.py
from flask import request, redirect, url_for

from modules.Language.form_validators.EditTranslationFormValidator import EditTranslationFormValidator
from modules.Language.services.LanguageService import LanguageService
from modules.Language.validator import LanguageValidator
from modules.Language.views.ACPTranslationEditView import ACPTranslationEditView
from modules.Language.views.ACPTranslationView import ACPTranslationView


class ACPTranslationController:

    def listAction(self):
        view = ACPTranslationView()
        languageService = LanguageService.getInstance()

        view.data = {'texts': languageService.texts}

        return view.render()

    def editPageAction(self):
        view = ACPTranslationEditView()
        languageService = LanguageService.getInstance()

        view.data = {'text': languageService.getTextByID(request.args.get('id'))}

        return view.render()

    def editAction(self):
        textID = int(request.args.get('id', 0))
        if (textID == 0 or not LanguageValidator.intID(textID, True)):
            return redirect(url_for('ACPTranslationPage', language=request.ctx['language']))

        languageService = LanguageService.getInstance()

        view = ACPTranslationEditView()
        
        formValidator = EditTranslationFormValidator(request.form)
        if formValidator.hasErrors:
            view.error('Form errors')
            view.data = {'text': languageService.getTextByID(textID)}
            view.data = {'formErrors': formValidator.errors}
            return view.render()

        data = formValidator.getFormData()
        data['textID'] = textID
        languageService.updateTranslations(data)
        
        view.data = {'text': languageService.getTextByID(textID)}
        
        return view.render()

app/modules/Language/controllers/TranslationACPController.py
import re

from flask import g, redirect, request, url_for
from modules.Language.form_validators.EditTranslationFormValidator import EditTranslationFormValidator
from modules.Language.services.LanguageService import LanguageService
from modules.Language.validators.LanguageValidator import LanguageValidator
from modules.Language.views.EditTranslationACPView import EditTranslationACPView
from modules.Language.views.TranslationsACPView import TranslationsACPView


class TranslationACPController:

    def __init__(self):
        self._languageService = LanguageService()

    def translationsPageAction(self):
        view = TranslationsACPView()

        view.data = {'texts': g.t.texts}

        return view.render()

    def editTranslationsPageAction(self):
        textID = int(request.args.get('id', 0))

        if (textID == 0 or not LanguageValidator.intID(textID, True)):
            return redirect(
                url_for(
                    'translationsACPBlueprint.translationsACPRoute',
                    language=g.current_language.code
                )
            )

        text = self._languageService.getTextByID(textID)

        if text is None:
            return redirect(
                url_for(
                    'translationsACPBlueprint.translationsACPRoute',
                    language=g.current_language.code
                )
            )

        view = EditTranslationACPView()
        view.data = {'text': text}

        return view.render()

    def editTranslationsAction(self):
        textID = int(request.args.get('id', 0))

        if (textID == 0 or not LanguageValidator.intID(textID, True)):
            return redirect(
                url_for(
                    'translationsACPBlueprint.translationsACPRoute',
                    language=g.current_language.code
                )
            )

        textEntity = self._languageService.getTextByID(textID)

        if textEntity is None:
            return redirect(
                url_for(
                    'translationsACPBlueprint.translationsACPRoute',
                    language=g.current_language.code
                )
            )

        formValidator = EditTranslationFormValidator(request.form)
        if formValidator.errors:
            view = EditTranslationACPView()
            view.error('Form errors')
            view.data = {
                'text': textEntity,
                'formErrors': formValidator.errors,
            }

            return view.render()

        data = formValidator.get_form_data()

        pattern = re.compile('translation_(' + '|'.join(g.t.languages.keys()) + ')')
        for fieldName, fieldValue in data.items():
            result = pattern.search(fieldName)
            if result:
                language = result.group(1)
                if language not in g.t.languages:
                    continue
                textEntity.translations[language] = fieldValue

        self._languageService.updateTextTranslations(textEntity)
        g.t.setTexts()

        return redirect(
            url_for(
                'translationsACPBlueprint.translationsACPRoute',
                language=g.current_language.code
            )
        )

    def deleteTextAction(self):
        textID = int(request.args.get('id', 0))

        if (textID == 0 or not LanguageValidator.intID(textID, True)):
            return redirect(
                url_for(
                    'translationsACPBlueprint.translationsACPRoute',
                    language=g.current_language.code
                )
            )

        self._languageService.deleteTranslations(textID)
        self._languageService.deleteText(textID)
        g.t.setTexts()

        return redirect(
            url_for(
                'translationsACPBlueprint.translationsACPRoute',
                language=g.current_language.code
            )
        )

app/modules/Language/routes/TranslationsACPBlueprint.py
from flask import Blueprint, request

from modules.Language.controllers.TranslationACPController import TranslationACPController
from modules.Session.requestDecorators import with_session
from request_decorators import with_language

translationsACPBlueprint = Blueprint(
    'translationsACPBlueprint',
    __name__,
    url_prefix='/<string:language>/acp/translations',
)
translationsACPController = TranslationACPController()


@translationsACPBlueprint.route('', methods=['GET'])
@with_language
@with_session
def translationsACPRoute():
    return translationsACPController.translationsPageAction()


@translationsACPBlueprint.route('/edit', methods=['GET', 'POST'])
@with_language
@with_session
def editTranslationACPRoute():
    if request.method == 'GET':
        return translationsACPController.editTranslationsPageAction()
    elif request.method == 'POST':
        return translationsACPController.editTranslationsAction()


@translationsACPBlueprint.route('/delete', methods=['GET'])
@with_language
@with_session
def deleteTranslationACPRoute():
    return translationsACPController.deleteTextAction()

app/modules/Language/routes/translationsACPBlueprint.py
from flask import Blueprint, request, redirect, url_for

from modules.Language.controllers.TranslationACPController import TranslationACPController
from modules.Language.requestDecorators import languageRedirect
from modules.Session.requestDecorators import withSession


translationsACPBlueprint = Blueprint('translationsACPBlueprint', __name__, url_prefix='/<string:language>/acp/translations')
translationsACPController = TranslationACPController()

@translationsACPBlueprint.route('', methods=['GET'])
@languageRedirect
@withSession
def translationsACPRoute():
    return translationsACPController.translationsPageAction()

@translationsACPBlueprint.route('/edit', methods=['GET', 'POST'])
@languageRedirect
@withSession
def editTranslationACPRoute():
    if request.method == 'GET':
        return translationsACPController.editTranslationsPageAction()
    elif request.method == 'POST':
        return translationsACPController.editTranslationsAction()

@translationsACPBlueprint.route('/delete', methods=['GET'])
@languageRedirect
@withSession
def deleteTranslationACPRoute():
    return translationsACPController.deleteTextAction()

app/modules/Language/views/ACPTranslationEditView.py
from modules.Language.services.LanguageService import LanguageService
from modules.Ukubuka.views.UkubukaACPView import UkubukaACPView


class ACPTranslationEditView(UkubukaACPView):

    def __init__(self):
        super().__init__('modules/Language/ACP/TranslationEdit.html')

    def _prepareTemplateData(self):
        super()._prepareTemplateData()

        languageService = LanguageService.getInstance()
        self.templateData['title'] = languageService.translate('Edit translation')

app/modules/Language/views/ACPTranslationView.py
from modules.Language.services.LanguageService import LanguageService
from modules.Ukubuka.views.UkubukaACPView import UkubukaACPView


class ACPTranslationView(UkubukaACPView):

    def __init__(self):
        super().__init__('modules/Language/ACP/Translation.html')

    def _prepareTemplateData(self):
        super()._prepareTemplateData()

        languageService = LanguageService.getInstance()
        self.templateData['title'] = languageService.translate('Translations')

app/modules/Language/views/EditTranslationACPView.py
from flask import g
from modules.Base.views.ACPView import ACPView


class EditTranslationACPView(ACPView):

    template: str = 'modules/Language/ACP/editTranslation.html'

    def _prepare_template_data(self):
        super()._prepare_template_data()

        self.template_data['title'] = g.t._('Edit translation')

app/modules/Language/views/TranslationsACPView.py
from flask import g
from modules.Base.views.ACPView import ACPView


class TranslationsACPView(ACPView):

    template: str = 'modules/Language/ACP/translations.html'

    def _prepare_template_data(self):
        super()._prepare_template_data()

        self.template_data['title'] = g.t._('Translations')

app/templates/modules/Language/ACP/Translation.html
{% extends 'layouts/acp/layout.html' %}

{% block content -%}

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>{{ 'text'|translate }}</th>
            {% for language in t.languages.values() %}
            <th>{{ language.name }}</th>
            {% endfor %}
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for text in texts %}
        <tr>
            <td>{{ text.ID }}</td>
            <td>{{ text.text }}</td>
            {% for languageCode in t.languages.keys() %}
            <td>{{ text.translations[languageCode] }}</td>
            {% endfor %}
            <td><a href="{{ url_for('ACPTranslationEditPage', language=t.language.code, id=text.ID) }}">{{ 'edit'|translate }}</a></td>
            <td><a href="/{{ t.language.code }}/acp/translations/delete?id={{ text.ID }}">{{ 'delete'|translate }}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{%- endblock %}

app/templates/modules/Language/ACP/TranslationEdit.html
{% extends 'layouts/acp/layout.html' %}

{% block content -%}

<form action="{{ url_for('ACPTranslationEditPage', language=t.language.code, id=text.ID) }}" method="POST">
    <div>
        <label for="text">{{ 'Text'|translate }}</label>
        <input type="text" name="text" id="text" value="{{ text.text }}" disabled>
    </div>
    {% for language in t.languages.values() %}
    {% set fieldName = 'translation_' ~ language.code %}
    {% set hasError = fieldName in formErrors %}
    <div>
        <label for="{{ fieldName }}">{{ language.name }}</label>
        {% if hasError %}
        {% for errorText in formErrors[fieldName] %}
        <p>{{ errorText }}</p>
        {% endfor %}
        {% endif %}
        <input
            class="{{ 'error' if hasError }}"
            type="text" id="{{ fieldName }}"
            name="{{ fieldName }}"
            value="{{ text.translations[language.code] }}"
            placeholder="{{ language.name }}"
        >
    </div>
        {% endfor %}
        <input type="submit">
</form>

{%- endblock %}

app/templates/modules/Language/ACP/editTranslation.html
{% extends 'layouts/ACP/layout.html' %}

{% block content %}

<form action="{{ url_for('translationsACPBlueprint.editTranslationACPRoute', language=t.language.code, id=text.ID) }}" method="POST">
    
    <div>
        <label for="text">{{ 'Text'|_ }}</label>
        <input type="text" name="text" id="text" value="{{ text.text }}" disabled>
    </div>
    
    {% for language in t.languages.values() %}
    
    {% set fieldName = 'translation_' ~ language.code %}
    {% set hasError = fieldName in formErrors %}
    
    <div>
        <label for="{{ fieldName }}">{{ language.name }}</label>

        {% if hasError %}
        {% for errorText in formErrors[fieldName] %}
        <p>{{ errorText }}</p>
        {% endfor %}
        {% endif %}

        <input class="{{ 'error' if hasError }}" type="text" id="{{ fieldName }}" name="{{ fieldName }}" value="{{ text.translations[language.code] }}" placeholder="{{ language.name }}">
    </div>
    
    {% endfor %}
    
    <input type="submit">

</form>

{% endblock %}

app/templates/modules/Language/ACP/editTranslations.html
{% extends 'layouts/acp/layout.html' %}

{% block content -%}

<form action="{{ url_for('translationsACPBlueprint.editTranslationACPRoute', language=t.language.code, id=text.ID) }}" method="POST">
    <div>
        <label for="text">{{ 'Text'|translate }}</label>
        <input type="text" name="text" id="text" value="{{ text.text }}" disabled>
    </div>
    {% for language in t.languages.values() %}
    {% set fieldName = 'translation_' ~ language.code %}
    {% set hasError = fieldName in formErrors %}
    <div>
        <label for="{{ fieldName }}">{{ language.name }}</label>
        {% if hasError %}
        {% for errorText in formErrors[fieldName] %}
        <p>{{ errorText }}</p>
        {% endfor %}
        {% endif %}
        <input
            class="{{ 'error' if hasError }}"
            type="text" id="{{ fieldName }}"
            name="{{ fieldName }}"
            value="{{ text.translations[language.code] }}"
            placeholder="{{ language.name }}"
        >
    </div>
        {% endfor %}
        <input type="submit">
</form>

{%- endblock %}

app/templates/modules/Language/ACP/translations.html
{% extends 'layouts/ACP/layout.html' %}

{% block content %}

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>{{ 'text'|_ }}</th>
            {% for language in t.languages.values() %}
            <th>{{ language.name }}</th>
            {% endfor %}
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for text in texts.values() %}
        <tr>
            <td>{{ text.ID }}</td>
            <td>{{ text.text }}</td>
            {% for languageCode in t.languages.keys() %}
            <td>{{ text.translations[languageCode] }}</td>
            {% endfor %}
            <td>
                <a href="{{ url_for('translationsACPBlueprint.editTranslationACPRoute', language=t.language.code, id=text.ID) }}">{{ 'edit'|_ }}</a>
                <a href="{{ url_for('translationsACPBlueprint.deleteTranslationACPRoute', language=t.language.code, id=text.ID) }}">{{ 'delete'|_ }}</a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}